export interface ThemeColors {
  background: string;
  surface: string;
  card: string;
  border: string;
  hover: string;
  primary: string;
  primaryForeground: string;
  text: string;
  textSecondary: string;
  accent: string;
}

export interface Theme {
  id: string;
  name: string;
  group: string;
  colors: ThemeColors;
}

export const themes: Theme[] = [
  // ── Core ──
  {
    id: 'dark',
    name: 'Dark',
    group: 'Core',
    colors: {
      background: '#0f0f0f',
      surface: '#1a1a1a',
      card: '#1e1e1e',
      border: '#2e2e2e',
      hover: '#2a2a2a',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      text: '#e5e5e5',
      textSecondary: '#a0a0a0',
      accent: '#3b82f6',
    },
  },
  {
    id: 'light',
    name: 'Light',
    group: 'Core',
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      card: '#ffffff',
      border: '#e2e8f0',
      hover: '#f1f5f9',
      primary: '#2563eb',
      primaryForeground: '#ffffff',
      text: '#0f172a',
      textSecondary: '#64748b',
      accent: '#2563eb',
    },
  },
  // ── Popular ──
  {
    id: 'dracula',
    name: 'Dracula',
    group: 'Popular',
    colors: {
      background: '#282a36',
      surface: '#2d2f3d',
      card: '#343746',
      border: '#44475a',
      hover: '#3c3f58',
      primary: '#bd93f9',
      primaryForeground: '#282a36',
      text: '#f8f8f2',
      textSecondary: '#6272a4',
      accent: '#ff79c6',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    group: 'Popular',
    colors: {
      background: '#2e3440',
      surface: '#3b4252',
      card: '#3b4252',
      border: '#434c5e',
      hover: '#434c5e',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      text: '#eceff4',
      textSecondary: '#d8dee9',
      accent: '#81a1c1',
    },
  },
  {
    id: 'onedark',
    name: 'One Dark',
    group: 'Popular',
    colors: {
      background: '#282c34',
      surface: '#2c313a',
      card: '#2c313a',
      border: '#3e4451',
      hover: '#3e4451',
      primary: '#61afef',
      primaryForeground: '#282c34',
      text: '#abb2bf',
      textSecondary: '#5c6370',
      accent: '#c678dd',
    },
  },
  {
    id: 'trueblack',
    name: 'True Black',
    group: 'Popular',
    colors: {
      background: '#000000',
      surface: '#0a0a0a',
      card: '#111111',
      border: '#1e1e1e',
      hover: '#1a1a1a',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      text: '#ffffff',
      textSecondary: '#888888',
      accent: '#3b82f6',
    },
  },
  // ── Stylish ──
  {
    id: 'aquamarine',
    name: 'Aquamarine',
    group: 'Stylish',
    colors: {
      background: '#132a13',
      surface: '#1a3a1a',
      card: '#1e4620',
      border: '#2d6a2e',
      hover: '#245428',
      primary: '#7fffd4',
      primaryForeground: '#132a13',
      text: '#d5f5e3',
      textSecondary: '#82c99e',
      accent: '#7fffd4',
    },
  },
  {
    id: 'plex',
    name: 'Plex',
    group: 'Stylish',
    colors: {
      background: '#1f1f1f',
      surface: '#252525',
      card: '#2a2a2a',
      border: '#383838',
      hover: '#333333',
      primary: '#e5a00d',
      primaryForeground: '#1f1f1f',
      text: '#eaeaea',
      textSecondary: '#999999',
      accent: '#e5a00d',
    },
  },
  {
    id: 'hotline',
    name: 'Hotline',
    group: 'Stylish',
    colors: {
      background: '#1a0a2e',
      surface: '#220e3a',
      card: '#2a1248',
      border: '#3d1a66',
      hover: '#331558',
      primary: '#ff2d95',
      primaryForeground: '#ffffff',
      text: '#f0e0ff',
      textSecondary: '#b088cc',
      accent: '#ff2d95',
    },
  },
  {
    id: 'hotpink',
    name: 'Hot Pink',
    group: 'Stylish',
    colors: {
      background: '#1c1021',
      surface: '#251529',
      card: '#2e1a33',
      border: '#452747',
      hover: '#3a2040',
      primary: '#ff69b4',
      primaryForeground: '#1c1021',
      text: '#f5e0ef',
      textSecondary: '#c090b0',
      accent: '#ff69b4',
    },
  },
  {
    id: 'spacegray',
    name: 'Space Gray',
    group: 'Stylish',
    colors: {
      background: '#20232a',
      surface: '#282c34',
      card: '#2c313a',
      border: '#3a3f4b',
      hover: '#353a45',
      primary: '#56b6c2',
      primaryForeground: '#20232a',
      text: '#d1d5db',
      textSecondary: '#7f848e',
      accent: '#56b6c2',
    },
  },
  {
    id: 'overseerr',
    name: 'Overseerr',
    group: 'Stylish',
    colors: {
      background: '#111827',
      surface: '#1f2937',
      card: '#1f2937',
      border: '#374151',
      hover: '#2d3748',
      primary: '#6366f1',
      primaryForeground: '#ffffff',
      text: '#f3f4f6',
      textSecondary: '#9ca3af',
      accent: '#818cf8',
    },
  },
  {
    id: 'maroon',
    name: 'Maroon',
    group: 'Stylish',
    colors: {
      background: '#1c0f0f',
      surface: '#241414',
      card: '#2c1a1a',
      border: '#4a2222',
      hover: '#3a1c1c',
      primary: '#b91c1c',
      primaryForeground: '#ffffff',
      text: '#f5d5d5',
      textSecondary: '#c08888',
      accent: '#ef4444',
    },
  },
  {
    id: 'organizr',
    name: 'Organizr',
    group: 'Stylish',
    colors: {
      background: '#1f1d2b',
      surface: '#252336',
      card: '#2a2840',
      border: '#3c3955',
      hover: '#33304a',
      primary: '#f9a825',
      primaryForeground: '#1f1d2b',
      text: '#e8e6f0',
      textSecondary: '#9895ad',
      accent: '#f9a825',
    },
  },
  {
    id: 'pineshadow',
    name: 'Pine Shadow',
    group: 'Stylish',
    colors: {
      background: '#0c1618',
      surface: '#12201f',
      card: '#172927',
      border: '#254240',
      hover: '#1d3533',
      primary: '#04a777',
      primaryForeground: '#ffffff',
      text: '#d8e8e4',
      textSecondary: '#6ba89e',
      accent: '#04a777',
    },
  },
  {
    id: 'ibracorp',
    name: 'Ibracorp',
    group: 'Stylish',
    colors: {
      background: '#0f0f1a',
      surface: '#161625',
      card: '#1c1c30',
      border: '#2a2a45',
      hover: '#22223a',
      primary: '#00b4d8',
      primaryForeground: '#0f0f1a',
      text: '#e0e0ff',
      textSecondary: '#7878a0',
      accent: '#00b4d8',
    },
  },
  // ── Catppuccin ──
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    group: 'Catppuccin',
    colors: {
      background: '#1e1e2e',
      surface: '#24243e',
      card: '#2a2a42',
      border: '#45475a',
      hover: '#35354e',
      primary: '#cba6f7',
      primaryForeground: '#1e1e2e',
      text: '#cdd6f4',
      textSecondary: '#6c7086',
      accent: '#f5c2e7',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    group: 'Catppuccin',
    colors: {
      background: '#eff1f5',
      surface: '#e6e9ef',
      card: '#e6e9ef',
      border: '#ccd0da',
      hover: '#dce0e8',
      primary: '#8839ef',
      primaryForeground: '#eff1f5',
      text: '#4c4f69',
      textSecondary: '#6c6f85',
      accent: '#ea76cb',
    },
  },
  {
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappé',
    group: 'Catppuccin',
    colors: {
      background: '#303446',
      surface: '#363a4f',
      card: '#3a3e55',
      border: '#51576d',
      hover: '#454a62',
      primary: '#ca9ee6',
      primaryForeground: '#303446',
      text: '#c6d0f5',
      textSecondary: '#737994',
      accent: '#f4b8e4',
    },
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    group: 'Catppuccin',
    colors: {
      background: '#24273a',
      surface: '#2a2d40',
      card: '#30334a',
      border: '#494d64',
      hover: '#3b3f55',
      primary: '#c6a0f6',
      primaryForeground: '#24273a',
      text: '#cad3f5',
      textSecondary: '#6e738d',
      accent: '#f5bde6',
    },
  },
  // ── Blackberry ──
  {
    id: 'blackberry-solar',
    name: 'Blackberry Solar',
    group: 'Blackberry',
    colors: {
      background: '#161618',
      surface: '#1c1c1f',
      card: '#222226',
      border: '#333338',
      hover: '#2a2a30',
      primary: '#f59e0b',
      primaryForeground: '#161618',
      text: '#e8e8e8',
      textSecondary: '#888888',
      accent: '#f59e0b',
    },
  },
  {
    id: 'blackberry-abyss',
    name: 'Blackberry Abyss',
    group: 'Blackberry',
    colors: {
      background: '#080810',
      surface: '#0e0e1a',
      card: '#141422',
      border: '#22223a',
      hover: '#1a1a2e',
      primary: '#4f46e5',
      primaryForeground: '#ffffff',
      text: '#d0d0e8',
      textSecondary: '#6868a0',
      accent: '#818cf8',
    },
  },
  {
    id: 'blackberry-amethyst',
    name: 'Blackberry Amethyst',
    group: 'Blackberry',
    colors: {
      background: '#120a1e',
      surface: '#1a1028',
      card: '#201535',
      border: '#35204a',
      hover: '#2a1a40',
      primary: '#a855f7',
      primaryForeground: '#ffffff',
      text: '#e8d8f8',
      textSecondary: '#8868a0',
      accent: '#c084fc',
    },
  },
  {
    id: 'blackberry-carol',
    name: 'Blackberry Carol',
    group: 'Blackberry',
    colors: {
      background: '#1a0808',
      surface: '#220e0e',
      card: '#2a1414',
      border: '#451e1e',
      hover: '#381818',
      primary: '#dc2626',
      primaryForeground: '#ffffff',
      text: '#f5d0d0',
      textSecondary: '#a07070',
      accent: '#f87171',
    },
  },
  {
    id: 'blackberry-dreamscape',
    name: 'Blackberry Dreamscape',
    group: 'Blackberry',
    colors: {
      background: '#0a0a14',
      surface: '#101020',
      card: '#16162a',
      border: '#262645',
      hover: '#1e1e38',
      primary: '#8b5cf6',
      primaryForeground: '#ffffff',
      text: '#d8d0f0',
      textSecondary: '#7868a0',
      accent: '#a78bfa',
    },
  },
  {
    id: 'blackberry-flamingo',
    name: 'Blackberry Flamingo',
    group: 'Blackberry',
    colors: {
      background: '#1a0a10',
      surface: '#220e18',
      card: '#2e1420',
      border: '#451e32',
      hover: '#3a1828',
      primary: '#ec4899',
      primaryForeground: '#ffffff',
      text: '#f5d0e0',
      textSecondary: '#a07088',
      accent: '#f472b6',
    },
  },
  {
    id: 'blackberry-hearth',
    name: 'Blackberry Hearth',
    group: 'Blackberry',
    colors: {
      background: '#1a100a',
      surface: '#221610',
      card: '#2e1c16',
      border: '#452e1e',
      hover: '#3a2418',
      primary: '#f97316',
      primaryForeground: '#1a100a',
      text: '#f5e0d0',
      textSecondary: '#a08870',
      accent: '#fb923c',
    },
  },
  {
    id: 'blackberry-martian',
    name: 'Blackberry Martian',
    group: 'Blackberry',
    colors: {
      background: '#0a1a0a',
      surface: '#102210',
      card: '#142e14',
      border: '#1e451e',
      hover: '#183a18',
      primary: '#22c55e',
      primaryForeground: '#0a1a0a',
      text: '#d0f5d0',
      textSecondary: '#70a070',
      accent: '#4ade80',
    },
  },
  {
    id: 'blackberry-pumpkin',
    name: 'Blackberry Pumpkin',
    group: 'Blackberry',
    colors: {
      background: '#1c0e02',
      surface: '#241406',
      card: '#2e1a0a',
      border: '#45280e',
      hover: '#3a200c',
      primary: '#ea580c',
      primaryForeground: '#ffffff',
      text: '#f5dcc8',
      textSecondary: '#a08060',
      accent: '#f97316',
    },
  },
  {
    id: 'blackberry-royal',
    name: 'Blackberry Royal',
    group: 'Blackberry',
    colors: {
      background: '#0a0818',
      surface: '#100e22',
      card: '#16142e',
      border: '#222044',
      hover: '#1c1a3a',
      primary: '#7c3aed',
      primaryForeground: '#ffffff',
      text: '#d8d0f5',
      textSecondary: '#7068a0',
      accent: '#8b5cf6',
    },
  },
  {
    id: 'blackberry-shadow',
    name: 'Blackberry Shadow',
    group: 'Blackberry',
    colors: {
      background: '#0a0a0a',
      surface: '#121212',
      card: '#181818',
      border: '#262626',
      hover: '#1e1e1e',
      primary: '#78716c',
      primaryForeground: '#ffffff',
      text: '#d6d3d1',
      textSecondary: '#78716c',
      accent: '#a8a29e',
    },
  },
  {
    id: 'blackberry-vanta',
    name: 'Blackberry Vanta',
    group: 'Blackberry',
    colors: {
      background: '#020202',
      surface: '#080808',
      card: '#0e0e0e',
      border: '#1a1a1a',
      hover: '#141414',
      primary: '#525252',
      primaryForeground: '#ffffff',
      text: '#c0c0c0',
      textSecondary: '#606060',
      accent: '#737373',
    },
  },
  // ── Infinity Stones ──
  {
    id: 'infinity-mind',
    name: 'Infinity Stones Mind',
    group: 'Infinity Stones',
    colors: {
      background: '#0f1a08',
      surface: '#152210',
      card: '#1c2e16',
      border: '#2b4522',
      hover: '#223a1c',
      primary: '#eab308',
      primaryForeground: '#0f1a08',
      text: '#e8f0d0',
      textSecondary: '#80a058',
      accent: '#facc15',
    },
  },
  {
    id: 'infinity-soul',
    name: 'Infinity Stones Soul',
    group: 'Infinity Stones',
    colors: {
      background: '#1c0c04',
      surface: '#241208',
      card: '#301a0e',
      border: '#4a2814',
      hover: '#3c2010',
      primary: '#f97316',
      primaryForeground: '#ffffff',
      text: '#f5dcc0',
      textSecondary: '#a08050',
      accent: '#fb923c',
    },
  },
  {
    id: 'infinity-reality',
    name: 'Infinity Stones Reality',
    group: 'Infinity Stones',
    colors: {
      background: '#1c0408',
      surface: '#24080e',
      card: '#300e16',
      border: '#4a1420',
      hover: '#3c101a',
      primary: '#dc2626',
      primaryForeground: '#ffffff',
      text: '#f5c0c8',
      textSecondary: '#a05060',
      accent: '#f87171',
    },
  },
  {
    id: 'infinity-power',
    name: 'Infinity Stones Power',
    group: 'Infinity Stones',
    colors: {
      background: '#14041c',
      surface: '#1c0824',
      card: '#240e30',
      border: '#38144a',
      hover: '#2e103c',
      primary: '#a855f7',
      primaryForeground: '#ffffff',
      text: '#e0c0f5',
      textSecondary: '#8050a0',
      accent: '#c084fc',
    },
  },
  {
    id: 'infinity-space',
    name: 'Infinity Stones Space',
    group: 'Infinity Stones',
    colors: {
      background: '#040814',
      surface: '#080e1c',
      card: '#0e1628',
      border: '#142040',
      hover: '#101a34',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      text: '#c0d0f5',
      textSecondary: '#5068a0',
      accent: '#60a5fa',
    },
  },
  {
    id: 'infinity-time',
    name: 'Infinity Stones Time',
    group: 'Infinity Stones',
    colors: {
      background: '#0c1408',
      surface: '#121c0e',
      card: '#1a2614',
      border: '#283a1e',
      hover: '#203018',
      primary: '#16a34a',
      primaryForeground: '#ffffff',
      text: '#c8f0d0',
      textSecondary: '#58a068',
      accent: '#4ade80',
    },
  },
  // ── Rosé Pine ──
  {
    id: 'rosepine',
    name: 'Rosé Pine',
    group: 'Rosé Pine',
    colors: {
      background: '#191724',
      surface: '#1f1d2e',
      card: '#26233a',
      border: '#393552',
      hover: '#2e2b44',
      primary: '#c4a7e7',
      primaryForeground: '#191724',
      text: '#e0def4',
      textSecondary: '#6e6a86',
      accent: '#ebbcba',
    },
  },
  {
    id: 'rosepine-moon',
    name: 'Rosé Pine Moon',
    group: 'Rosé Pine',
    colors: {
      background: '#232136',
      surface: '#2a273f',
      card: '#312e4a',
      border: '#44415a',
      hover: '#3b3852',
      primary: '#c4a7e7',
      primaryForeground: '#232136',
      text: '#e0def4',
      textSecondary: '#6e6a86',
      accent: '#ea9a97',
    },
  },
  {
    id: 'rosepine-dawn',
    name: 'Rosé Pine Dawn',
    group: 'Rosé Pine',
    colors: {
      background: '#faf4ed',
      surface: '#fffaf3',
      card: '#f2e9e1',
      border: '#dfdad9',
      hover: '#f2e9de',
      primary: '#907aa9',
      primaryForeground: '#faf4ed',
      text: '#575279',
      textSecondary: '#797593',
      accent: '#d7827e',
    },
  },
  // ── SnowShelf Special ──
  {
    id: 'snowshelf-christmas',
    name: 'SnowShelf Christmas',
    group: 'SnowShelf',
    colors: {
      background: '#0c1a0c',
      surface: '#122012',
      card: '#1a2e1a',
      border: '#244524',
      hover: '#1e381e',
      primary: '#dc2626',
      primaryForeground: '#ffffff',
      text: '#d0f0d0',
      textSecondary: '#68a068',
      accent: '#22c55e',
    },
  },
  {
    id: 'snowshelf-santa',
    name: 'SnowShelf Santa',
    group: 'SnowShelf',
    colors: {
      background: '#1c0808',
      surface: '#240e0e',
      card: '#2e1414',
      border: '#451e1e',
      hover: '#381818',
      primary: '#ef4444',
      primaryForeground: '#ffffff',
      text: '#f5d5d5',
      textSecondary: '#a07878',
      accent: '#fbbf24',
    },
  },
  {
    id: 'snowshelf-halloween',
    name: 'SnowShelf Halloween',
    group: 'SnowShelf',
    colors: {
      background: '#0e0a04',
      surface: '#161008',
      card: '#1e160c',
      border: '#302210',
      hover: '#261c0e',
      primary: '#f97316',
      primaryForeground: '#0e0a04',
      text: '#f0dcc0',
      textSecondary: '#a08850',
      accent: '#a855f7',
    },
  },
];

export const themeGroups = [...new Set(themes.map((t) => t.group))];

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}
